import { Creator, AudienceProfile, Product } from './types';

export const MOCK_CREATOR: Creator = {
  id: 'mock_001',
  name: 'Priya Sharma',
  username: 'priya.styles',
  profile_pic: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
  follower_count: 48200,
  bio: 'Fashion & lifestyle creator | OOTD everyday ✨',
  niche: 'fashion',
  onboarding_complete: false,
};

export const MOCK_AUDIENCE: AudienceProfile = {
  age_distribution: {
    '13-17': 8,
    '18-24': 45,
    '25-34': 32,
    '35-44': 11,
    '45+': 4,
  },
  gender: { female: 74, male: 23, other: 3 },
  top_locations: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Pune'],
  income_bracket: 'lower-middle',
  interests: ['fashion', 'beauty', 'lifestyle'],
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p001',
    name: 'Floral Anarkali Kurta Set',
    category: "Women's Ethnic",
    price_range: '₹399–₹799',
    commission_pct: 15,
    niche_tags: ['fashion', 'lifestyle'],
    image_url: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=400&fit=crop',
    match_score: 96,
    description: 'Trending ethnic wear loved by fashion creators',
  },
  {
    id: 'p002',
    name: 'Printed Co-ord Set',
    category: "Women's Western",
    price_range: '₹499–₹999',
    commission_pct: 18,
    niche_tags: ['fashion'],
    image_url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop',
    match_score: 93,
    description: 'Instagram-ready co-ord sets for modern creators',
  },
  {
    id: 'p003',
    name: 'Embroidered Dupatta',
    category: 'Accessories',
    price_range: '₹199–₹499',
    commission_pct: 20,
    niche_tags: ['fashion', 'beauty'],
    image_url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=400&fit=crop',
    match_score: 91,
    description: 'High-margin accessory with wide audience appeal',
  },
  {
    id: 'p004',
    name: 'Casual Palazzo Set',
    category: "Women's Fusion",
    price_range: '₹349–₹699',
    commission_pct: 16,
    niche_tags: ['fashion', 'lifestyle'],
    image_url: 'https://images.unsplash.com/photo-1551489186-cf8726f514f8?w=400&h=400&fit=crop',
    match_score: 89,
    description: 'Comfort-first fashion that sells year-round',
  },
  {
    id: 'p005',
    name: 'Festive Lehenga Choli',
    category: "Women's Ethnic",
    price_range: '₹799–₹1,499',
    commission_pct: 14,
    niche_tags: ['fashion'],
    image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&h=400&fit=crop',
    match_score: 87,
    description: 'High-value festive wear with great commissions',
  },
  {
    id: 'p006',
    name: 'Vitamin C Serum',
    category: 'Skincare',
    price_range: '₹249–₹499',
    commission_pct: 22,
    niche_tags: ['beauty', 'lifestyle'],
    image_url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    match_score: 85,
    description: 'Top-selling skincare with high repeat purchase rate',
  },
  {
    id: 'p007',
    name: 'Makeup Brush Set',
    category: 'Beauty Tools',
    price_range: '₹199–₹399',
    commission_pct: 25,
    niche_tags: ['beauty'],
    image_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
    match_score: 82,
    description: 'Essential beauty kit — great gifting product',
  },
  {
    id: 'p008',
    name: 'Scented Soy Candle Set',
    category: 'Home Decor',
    price_range: '₹299–₹599',
    commission_pct: 18,
    niche_tags: ['home', 'lifestyle'],
    image_url: 'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?w=400&h=400&fit=crop',
    match_score: 79,
    description: 'Aesthetic home products trending on Reels',
  },
];
